# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, max_length=300)),
                ('exec_time', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
